[package]
name = "weecord"
version = "0.1.0"
authors = ["Porter Smith <flowbish@gmail.com>", "khyperia <khyperia@live.com>", "Noskcaj <kcajdev@gmail.com>"]
build = "build.rs"
edition = "2018"

[build-dependencies]
pkg-config = "0.3.14"
cc = "1.0.28"

[lib]
name = "weecord"
crate-type = ["dylib"]

[dependencies]
libc = "0.2.46"
lazy_static = "1.2.0"
dirs = "1.0.4"
crossbeam-channel = "0.3.6"

[dependencies.serenity]
git = "https://github.com/terminal-discord/serenity"
default_features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "utils"
]

[dependencies.parsing]
path = "parsing"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }

